---
title: "Soil properties interaction T0 T4"
author: "Raquel Correa"
date: "2023-11-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



``` {r, include=FALSE}
library(ggplot2)
library(tidyverse)
library(ggpubr)
library(gridExtra)
library(corrplot)
library(agricolae)
library(emmeans)
library(multcomp)
library(multcompView)
library(data.table)
library(tidyverse)

library(phyloseq)

library(vegan)
library(ape)
library(here)
library(readxl)
library(ggpubr)
library(geomtextpath)
library(knitr)
library(gridExtra)
library(Biostrings)
library(seqinr)
library(FSA)
library(agricolae)
library(MASS)
library(grid)
library(gridExtra)
library(emmeans)
library(multcomp)
library(broom)
library(viridis)

#install.packages("ALDEx2")
library(ALDEx2)
library(FactoMineR)
library(factoextra)
library(kableExtra)
library(scales)
library(dunn.test)
library(car)
library(corrplot)
library(eulerr)
library(ggforce)
library(ggrepel)
library(rstatix)
library(AICcmodavg)
library(ggthemes)
library(lme4)
library(lmerTest)

```

### Differences between the beginning at the end of the experiment (T0 vs T4)


```{r colors, include=FALSE}
treat.colors <- c("control"= "green4" ,"control.amf"  = "darkseagreen" , "chicken.manure"= "royalblue1", "cow.manure" = "red3","mo.pellet"= "darkorchid1","compost"="chocolate4","control.legume"="darkolivegreen4")
treat.colors
treat.order <- c('control', 'control.amf', 'control.legume', "compost", "chicken.manure", "cow.manure", "mo.pellet") 
treat.labels <- c("Control", "Control\nAMF", "Control\nLegume", "Compost", "Chicken\nmanure", "Cow\nmanure", "Pellet")

```

```{r Import, include=FALSE}
#Esto se ha hecho para cargar el Excel de los datos iniciales (ojo, para poner el directorio de donde esta tu archivo excel, se tiene que cambiar \, por /), y para hacer la media de cada tratamiento, ya que de cada tratamiento hay 3 repeticiones. El simbolo %>% se llaman tuberias (the pipe) vienen de la libreria (tinyverse) (esta libreria sirve para mantener R más ordenado). Las tuberias funcionan usando el resultado de una operación(out) y convirtiendolo en el imput de otra. En el caso del codigo  "soil.summ <- soil_prop %>% group_by(treatment,  time) %>% summarise(across(.cols=everything(), .fns=mean),.groups = "drop")" quiere decir lo siguiente: hemos creado un objeto nuevo que es soil.summ, que es_ el archivo de excel soil_prop el que hacemos una serie de operaciones en cadena (tuberia) donde agrupamos solamente por tratamiento y tiempo (group_by,) y en ese agrupamiento queremos de todas las columnas, .cols=every, que haga la funcion de la media (fns=mean). NULL significa que no tenga en cuenta esas columnas. $ es para seleccionar cosas especificas. 

soil_prop <- readxl::read_excel("C:/Users/Raquel/Documents/banana_microbiome/raw_files/soil_prop_2.xlsx")

treat.pot <- paste(soil_prop$treatment, soil_prop$rep, sep= "_") #para mantener el error

soil_prop <- data.frame(soil_prop, treat.pot)

#soil.summ <- soil_prop %>% group_by(treatment,  time) %>% summarise(across(.cols=everything(),.fns=mean),.groups = "drop")

soil.summ.sd <- soil_prop %>% group_by(treatment,  time) %>% 
  summarise(across(.cols=everything(),.fns=list(mean = mean, sd = sd)),.groups = "drop")

soil.summ.sd$rep_mean <- NULL
soil.summ.sd$soil.id_mean <- NULL
soil.summ.sd$rep_sd <- NULL

```


```{r stats orgmatter t0t4, include=TRUE}
soilt0t4 <- soil_prop %>% filter(time == "t0" | time == "t4") #data only t0 and t4
soilt0t4
soil_t0t4_mean <- soilt0t4 %>% group_by(treatment,  time) %>% 
  summarise(across(.cols=everything(),.fns=list(mean = mean, sd = sd)),.groups = "drop")

shapiro.test(soilt0t4$org.matter) #no normal data
soilt0t4 %>% group_by(treatment) %>% shapiro_test(org.matter) # each treatments are normal 
ggqqplot(data = soilt0t4, "org.matter", facet.by = "treatment")
leveneTest(org.matter ~ time * treatment, data=soilt0t4) #equal variances 
#anova_orgt0t4 <- aov(org.matter ~ time + treatment, data=soilt0t4) #anova two ways
#summary(anova_orgt0t4)
model_orgt0t4 <- lmer(org.matter~ time*treatment + (1|treat.pot), data=soilt0t4) 
summary(model_orgt0t4)

anova_modelorgt0t4 <- anova(model_orgt0t4)
anova_modelorgt0t4

emm_org <- emmeans(model_orgt0t4, pairwise ~ time | treatment)
emm_org
emm_org$contrasts %>% rbind(adjust= "fdr") %>% summary(infer = TRUE)#el adjust es para el metodo de los pvalues

#Estimaciones de Medias (Emmeans):Las estimaciones de medias para t0 y t4 proporcionan una visión de la tendencia general en cada tratamiento.Puedes observar cómo las medias cambian de t0 a t4 para cada tratamiento.Contrastes:Los contrastes (t0 - t4) indican la dirección y magnitud de cambio entre t0 y t4 para cada tratamiento.Un valor p bajo (p < 0.05) en un contraste sugiere que hay una diferencia significativa entre t0 y t4 para ese tratamiento.


#El ANOVA evalúa si hay alguna diferencia significativa en al menos una de las medias entre los grupos.Las comparaciones de medias (emmeans) evalúan diferencias específicas entre pares de niveles o combinaciones de niveles, proporcionando una visión más detallada.

orgcontras <- data.frame(emm_org$contrasts)#data frame para sacar el valor del contraste 
orgcontras
orgemmeans <- data.frame(emm_org$emmeans) %>% group_by(treatment) %>% summarise(across(.cols= "emmean",.fns=mean),.groups = "drop")#para sacar el valor solo de emmeans
orgemmeans

emm_org <- cld(emmeans(model_orgt0t4, specs = pairwise~treatment), Letters= letters, reversed= TRUE)#dif sig y las letras se lo indicas 
emm_org #tabla con los resultados. Se hacen dataframe para sacar las columnas que queremos y poder unirlas en los graficos 

pval.org.mat_emmeans <- data.frame(treatment= orgcontras$treatment, pval= orgcontras$p.value, emmean= orgemmeans$emmean)
pval.org.mat_emmeans
pval.org.mat_emmeans$sign <- ifelse(pval.org.mat_emmeans$pval>0.05, paste("ns"),
                                 ifelse(pval.org.mat_emmeans$pval>0.01, paste("*"),
                                        ifelse(pval.org.mat_emmeans$pval> 0.001,
                                               paste("**"), paste("***"))))#para add la significancia con el condicional ifelse


orgmattert0t4_time <- soil_t0t4_mean %>% ggplot(aes(x=factor(treatment, level= treat.order), y= org.matter_mean), col=time)+
  geom_col(aes(fill= time), col= "black", position= "dodge")+
  xlab("")+
  ylab("oxidable organic matter (%)")+
  theme_classic2()+
  scale_x_discrete(labels= treat.labels)+
  geom_text(data = pval.org.mat_emmeans, aes(x= treatment, y= emmean, label= sign), nudge_x= 0, nudge_y= 0.5)+
  geom_errorbar(data=soil_t0t4_mean, aes(ymin=org.matter_mean-org.matter_sd, 
                                            ymax=org.matter_mean+org.matter_sd, group= time), position=position_dodge(0.9),
                                            linewidth =0.2, width=0.2)+
  labs(title = "", subtitle = "", caption = "Different (*) indicates differences between the levels of the treatment factor at each time (T0-T4).\n caculated by Estimated Marginal Means post hoc -Tukey's adjustment method", size = 10)+
  ggtitle("OM (%) in T0 and T4\nMean and SD", subtitle= paste("LMEs-Anova III-Time:Treatment(Tukey) p-value: ", format(anova_modelorgt0t4$`Pr(>F)`[[3]], scientific= TRUE, digits=2 ), sep= ""))+
  guides(fill=guide_legend(title="Treatment"))+
  scale_fill_manual(values = c("#458B74", "#66CDAA"))+ # Add your desired colors
  guides(fill=guide_legend(title="Time"))+
  theme(
    plot.title = element_text(size = 12),
    plot.subtitle = element_text(size = 11),
    plot.caption = element_text(size = 9))

orgmattert0t4_time

ggsave(orgmattert0t4_time, file="soil_parameters_result/orgmattert0t4_time.png", width= 1900,height= 1200, units= "px")


#para hacer el delta, es decir cuanto ha variado la materia organica.. Hay que tener los archivos x separado  
mat.org.t0 <- subset(soilt0t4, soilt0t4$time == "t0")
mat.org.t0 <- data.frame( treatment=mat.org.t0$treatment, org.matter.t0= mat.org.t0$org.matter)
mat.org.t4 <- subset(soilt0t4, soilt0t4$time == "t4")
mat.org.t4 <- data.frame( treatment=mat.org.t4$treatment, org.matter.t4= mat.org.t4$org.matter)

delta.mat.org <- data.frame(treatment= mat.org.t0$treatment,t4= mat.org.t4$org.matter.t4 ,t0= mat.org.t0$org.matter.t0)
delta.mat.org$delta <- delta.mat.org$t4-delta.mat.org$t0
#delta.mat.org$ratio <- delta.mat.org$t4/delta.mat.org$t0
delta.mat.org

# Create a 'time' variable
#delta.mat.org$time <- rep(c("t0", "t4"), length.out = nrow(delta.mat.org))


delta.org.lm <- lm(delta ~ 0+treatment, data=delta.mat.org) #modelo normal respecto a 0
delta.org.lm 
anova_deltaorgt0t4 <-anova(delta.org.lm)#3.973e-06 ***
anova_deltaorgt0t4
emm_delta_org_lm <- emmeans(delta.org.lm, pairwise ~  treatment)
emm_delta_org_lm
emm_delta_org_lm$contrasts %>% rbind(adjust= "fdr") %>% summary(infer = TRUE)
#emm_delta_org_lm <- cld(emmeans(delta.org.lm, specs = pairwise~treatment), Letters= letters, reversed= TRUE)
emm_delta_org_lm


plotdeltaorg <- delta.mat.org %>% ggplot(aes(x=factor(treatment, level= treat.order), y= delta, fill= treatment))+
  geom_point(pch= 23, size= 7)+
  xlab("")+
  ylab("OM (%) Δ variation between t4-t0")+
  geom_hline(yintercept= 0, linetype = "dashed", color = "red")+
  scale_fill_manual(values= treat.colors)+
  geom_text(data= emm_delta_org_lm, aes(x= treatment, y= emmean, label= `.group`), nudge_x = 0.2, nudge_y = 0.2)+
  guides(fill=guide_legend(title="Treatment"))+
  scale_x_discrete(labels= treat.labels)+
  theme_classic2()+
  labs(title = "", subtitle = "", caption = "Different letters indicates differences between the levels of the treatment factor in delta variation (T4-T0).\n caculated by Estimated Marginal Means post hoc -Tukey's adjustment method.", size = 10)+
  ggtitle("OM (%) Δ variation T0 between T4", subtitle= paste("LinealModel-Anova Treatment(Tukey) p-value: ", format(anova_deltaorgt0t4$`Pr(>F)`[[1]], scientific= TRUE, digits=2 ), sep= ""))+
  theme(
    plot.title = element_text(size = 11),
    plot.subtitle = element_text(size = 10),
    plot.caption = element_text(size = 8))

plotdeltaorg
#Positive values in the delta column indicate an increase in org.matter from t0 to t4.
#Negative values in the delta column indicate a decrease in org.matter from t0 to t4.
ggsave(plotdeltaorg, file="soil_parameters_result/deltaorgmattert0t4.png", width= 1900,height= 1200, units= "px")


#unir los dos graficos
orgt0t4 <- ggarrange(orgmattert0t4_time, plotdeltaorg)
orgt0t4

ggsave(orgt0t4, file="soil_parameters_result/orgt0t4.png", width= 3800,height= 2200, units= "px")

```



```{r delta nuevo, echo=TRU}
delta.mat.org
delta.org.lm0 <- lm(delta ~ 0+treatment, data=delta.mat.org) #modelo normal respecto a 0
summary(delta.org.lm0) 
newanova_deltaorgt0t4 <-anova(delta.org.lm)#3.973e-06 ***
newanova_deltaorgt0t4
dp_val_orgt0t4 <- summary(delta.org.lm0)$coefficient%>%
  as.data.frame()%>%
  rownames_to_column(var= "treatment")
dp_val_orgt0t4
dp_val_orgt0t4$treatment<-sub("treatment", "", dp_val_orgt0t4$treatment)#add sig. que no sean lettras
dp_val_orgt0t4$sign <- ifelse(dp_val_orgt0t4$`Pr(>|t|)`<0.05, "*", "ns")
dp_val_orgt0t4$sign <- ifelse(dp_val_orgt0t4$`Pr(>|t|)`>0.05, paste("ns"),
                                 ifelse(dp_val_orgt0t4$`Pr(>|t|)`>0.01, paste("*"),
                                        ifelse(dp_val_orgt0t4$`Pr(>|t|)`> 0.001,
                                               paste("**"), paste("***"))))#para add la

dp_val_orgt0t4
#dp_val_orgt0t4$size <- ifelse(dp_val_orgt0t4$sign== "*", 8, 4)
#dp_val_orgt0t4$size <- as.numeric(dp_val_orgt0t4$size)
dp_val_orgt0t4


plotdeltaorgnew <- delta.mat.org %>% ggplot(aes(x=factor(treatment, level= treat.order), y= delta, fill= treatment))+
  geom_point(pch= 23, size= 7)+
  xlab("")+
  ylab("OM (%)\u0394 variation between t4-t0")+
  geom_hline(yintercept= 0, linetype = "dashed", color = "red")+
  scale_fill_manual(values= treat.colors)+
  geom_text(data = dp_val_orgt0t4, aes(x = treatment, y = Estimate, label = sign),
            position = position_dodge(width = 0.8), vjust = -0.5, size = 8)+
  guides(fill=guide_legend(title="Treatment"))+
  scale_x_discrete(labels= treat.labels)+
  theme_classic2()+
  stat_summary(fun=mean, aes(x= treatment, y = delta),geom= "crossbar", width=0.5, colour= "grey20", data=delta.mat.org)+
  labs(title = "", subtitle = "", caption = "Different letters indicates differences between the levels of the treatment factor in delta variation (T4-T0).\n caculated by Estimated Marginal Means post hoc -Tukey's adjustment method.", size = 10)+
  ggtitle("OM (%) Δ variation T0 between T4", subtitle= paste("LinealModel-Anova Treatment(Tukey) p-value: ", format(anova_deltaorgt0t4$`Pr(>F)`[[1]], scientific= TRUE, digits=2 ), sep= ""))+
  theme(
    plot.title = element_text(size = 11),
    plot.subtitle = element_text(size = 10),
    plot.caption = element_text(size = 8))

plotdeltaorgnew




d.pval.even$size <- ifelse(d.pval.even$sign== "*", 8, 4)
d.pval.even$size <- as.numeric(d.pval.even$size)
d.even.plot <- data.delta %>% ggplot(aes( factor(treatment, level= treat.order), d.even))+
  geom_point(shape= 23, size = 4, col= "black", aes(fill= treatment))+
  geom_hline(yintercept = 0, linetype= 2 )+
  geom_text(data= d.pval.even,aes(treatment, 0.02, label = sign),
            size=d.pval.even$size)+
  ylab("\u0394evenness (T5-T0)")+
  xlab("Treatment")+
  scale_fill_manual(values= treat.colors)+
  scale_color_manual(values= treat.colors)+
  scale_x_discrete(label= treat.labels)+
  stat_summary(aes(x= treatment, y = d.even, group = treatment, col= treatment),fun= mean, geom = "crossbar", linewidth= 0.5, show.legend = FALSE)+
  theme_classic2()+
  ggtitle("Variation in evenness")+
  guides(fill=guide_legend(title="Treatment"))
d.even.plot


```




```{r stas phosphorus t0t4, echo=FALSE}
shapiro.test(soilt0t4$phosphorus) #no normal data
soilt0t4 %>% group_by(treatment) %>% shapiro_test(phosphorus) # no normal data. the group of each data are normal in t0 and t4.
leveneTest(phosphorus ~ time * treatment, data=soilt0t4) #equal variances 
model_phosphot0t4 <- lmer(phosphorus~ time*treatment + (1|treat.pot), data=soilt0t4) 
summary(model_phosphot0t4)

anova_modelphosphot0t4 <- anova(model_phosphot0t4)
anova_modelphosphot0t4

emm_phospho <- emmeans(model_phosphot0t4, pairwise ~ time | treatment)
emm_phospho
emm_phospho$contrasts %>% rbind(adjust= "fdr") %>% summary(infer = TRUE)#el adjust es para el 
phosphocontras <- data.frame(emm_phospho$contrasts)#data frame para sacar el valor del contraste 
phosphocontras
phosphoemmeans <- data.frame(emm_phospho$emmeans) %>% group_by(treatment) %>% summarise(across(.cols= "emmean",.fns=mean),.groups = "drop")#para sacar el valor solo de emmeans
phosphoemmeans

emm_phospho <- cld(emmeans(model_phosphot0t4, specs = pairwise~treatment), Letters= letters, reversed= TRUE)#dif sig y las letras se lo indicas 
emm_phospho #tabla con los resultados. Se hacen dataframe para sacar las columnas que queremos y poder unirlas en los graficos 

pval.phospho_emmeans <- data.frame(treatment= phosphocontras$treatment, pval= phosphocontras$p.value, emmean= phosphoemmeans$emmean)
pval.phospho_emmeans
pval.phospho_emmeans$sign <- ifelse(pval.phospho_emmeans$pval>0.05, paste("ns"),
                                 ifelse(pval.phospho_emmeans$pval>0.01, paste("*"),
                                        ifelse(pval.phospho_emmeans$pval> 0.001,
                                               paste("**"), paste("***"))))#para add la significancia con el condicional ifelse


phosphot0t4_time <- soil_t0t4_mean %>% ggplot(aes(x=factor(treatment, level= treat.order), y= phosphorus_mean), col=time)+
  geom_col(aes(fill= time), col= "black", position= "dodge")+
  xlab("")+
  ylab("Phosphorus (mg/kg)")+
  theme_classic2()+
  scale_x_discrete(labels= treat.labels)+
  geom_text(data = pval.phospho_emmeans, aes(x= treatment, y= emmean, label= sign), nudge_x= 0, nudge_y= 12)+
  geom_errorbar(data=soil_t0t4_mean, aes(ymin=phosphorus_mean-phosphorus_sd, 
                                            ymax=phosphorus_mean+phosphorus_sd, group= time), position=position_dodge(0.9),linewidth =0.2, width=0.2)+
  labs(title = "", subtitle = "", caption = "Different (*) indicates differences between the levels of the treatment factor at each time (T0-T4).\n caculated by Estimated Marginal Means post hoc -Tukey's adjustment method", size = 10)+
  ggtitle("Phosphorus (mg/kg) in T0 and T4\nMean and SD", subtitle= paste("LMEs-Anova III-Time:Treatment(Tukey) p-value: ", format(anova_modelphosphot0t4$`Pr(>F)`[[3]], scientific= TRUE, digits=2 ), sep= ""))+
  guides(fill=guide_legend(title="Treatment"))+
  scale_fill_manual(values = c("#458B74", "#66CDAA"))+ # Add your desired colors
  guides(fill=guide_legend(title="Time"))+
  theme(
    plot.title = element_text(size = 12),
    plot.subtitle = element_text(size = 11),
    plot.caption = element_text(size = 9))

phosphot0t4_time
ggsave(phosphot0t4_time, file="soil_parameters_result/phosphot0t4_time.png", width= 1900,height= 1200, units= "px")


#para hacer el delta, es decir cuanto ha variado la materia organica.. Hay que tener los archivos x separado  
phospho.t0 <- subset(soilt0t4, soilt0t4$time == "t0")
phospho.t0 <- data.frame( treatment=phospho.t0$treatment, phosphorus.t0= phospho.t0$phosphorus)
phospho.t4 <- subset(soilt0t4, soilt0t4$time == "t4")
phospho.t4 <- data.frame( treatment=phospho.t4$treatment, phosphorus.t4= phospho.t4$phosphorus)

delta.phospho <- data.frame(treatment= phospho.t0$treatment,t4= phospho.t4$phosphorus.t4 ,t0= phospho.t0$phosphorus.t0)
delta.phospho$delta <- delta.phospho$t4-delta.phospho$t0
#delta.mat.org$ratio <- delta.mat.org$t4/delta.mat.org$t0
delta.phospho

delta.phospho.lm <- lm(delta ~ treatment, data=delta.phospho) #modelo normal 
delta.phospho.lm 
anova_deltaphosphot0t4 <-anova(delta.phospho.lm)#p value 0.005198
anova_deltaphosphot0t4
emm_delta_phospho_lm <- emmeans(delta.phospho.lm, pairwise ~  treatment)
emm_delta_phospho_lm
emm_delta_phospho_lm$contrasts %>% rbind(adjust= "fdr") %>% summary(infer = TRUE)
emm_delta_phospho_lm <- cld(emmeans(delta.phospho.lm, specs = pairwise~treatment), Letters= letters, reversed= TRUE)
emm_delta_phospho_lm


plotdeltaphospho <- delta.phospho %>% ggplot(aes(x=factor(treatment, level= treat.order), y= delta, fill= treatment))+
  geom_point(pch= 23, size= 7)+
  xlab("")+
  ylab("phosphorus Δ variation between t4-t0")+
  geom_hline(yintercept= 0, linetype = "dashed", color = "red")+
  scale_fill_manual(values= treat.colors)+
  geom_text(data= emm_delta_phospho_lm, aes(x= treatment, y= emmean, label= `.group`), nudge_x = 0.2, nudge_y = 0.2)+
  guides(fill=guide_legend(title="Treatment"))+
  scale_x_discrete(labels= treat.labels)+
  theme_classic2()+
  labs(title = "", subtitle = "", caption = "Different letters indicates differences between the levels of the treatment factor in delta variation (T4-T0).\n caculated by Estimated Marginal Means post hoc -Tukey's adjustment method.", size = 10)+
  ggtitle("Phosphorus mg/kg Δ variation T0 between T4", subtitle= paste("LinealModel-Anova Treatment(Tukey) p-value: ", format(anova_deltaphosphot0t4$`Pr(>F)`[[1]], scientific= TRUE, digits=2 ), sep= ""))+
  theme(
    plot.title = element_text(size = 11),
    plot.subtitle = element_text(size = 10),
    plot.caption = element_text(size = 8))

plotdeltaphospho
#Positive values in the delta column indicate an increase in org.matter from t0 to t4.
#Negative values in the delta column indicate a decrease in org.matter from t0 to t4.
ggsave(plotdeltaphospho, file="soil_parameters_result/plotdeltaphosphot0t4.png", width= 1900,height= 1200, units= "px")

#ver cuanto de diferente ha sido la variacion delta con respecto a 0

#unir los dos graficos
phosphot0t4 <- ggarrange(phosphot0t4_time, plotdeltaphospho)
phosphot0t4
ggsave(phosphot0t4, file="soil_parameters_result/phosphot0t4.png", width= 3800,height= 2200, units= "px")

```




```{r stats ph water t0t4, echo=FALSE}
shapiro.test(soilt0t4$ph.water) #no normal data
soilt0t4 %>% group_by(treatment) %>% shapiro_test(ph.water) # each treatment are normal.
leveneTest(ph.water~ time * treatment, data=soilt0t4) #equal variances 
model_ph.watert0t4 <- lmer(ph.water~ time*treatment + (1|treat.pot), data=soilt0t4) 
summary(model_ph.watert0t4)

anova_modelph.watert0t4 <- anova(model_ph.watert0t4)
anova_modelph.watert0t4

emm_ph.water <- emmeans(model_ph.watert0t4, pairwise ~ time | treatment)
emm_ph.water
emm_ph.water$contrasts %>% rbind(adjust= "fdr") %>% summary(infer = TRUE)#el adjust es para el 
ph.watercontras <- data.frame(emm_ph.water$contrasts)#data frame para sacar el valor del contraste 
ph.watercontras
ph.wateremmeans <- data.frame(emm_ph.water$emmeans) %>% group_by(treatment) %>% summarise(across(.cols= "emmean",.fns=mean),.groups = "drop")#para sacar el valor solo de emmeans
ph.wateremmeans

emm_ph.water <- cld(emmeans(model_ph.watert0t4, specs = pairwise~treatment), Letters= letters, reversed= TRUE)#dif sig y las letras se lo indicas 
emm_ph.water #tabla con los resultados. Se hacen dataframe para sacar las columnas que queremos y poder unirlas en los graficos 

pval.ph.water_emmeans <- data.frame(treatment= ph.watercontras$treatment, pval= ph.watercontras$p.value, emmean= ph.wateremmeans$emmean)
pval.ph.water_emmeans
pval.ph.water_emmeans$sign <- ifelse(pval.ph.water_emmeans$pval>0.05, paste("ns"),
                                 ifelse(pval.ph.water_emmeans$pval>0.01, paste("*"),
                                        ifelse(pval.ph.water_emmeans$pval> 0.001,
                                               paste("**"), paste("***"))))#para add la significancia con el condicional ifelse


ph.watert0t4_time <- soil_t0t4_mean %>% ggplot(aes(x=factor(treatment, level= treat.order), y= ph.water_mean), col=time)+
  geom_col(aes(fill= time), col= "black", position= "dodge")+
  xlab("")+
  ylab("ph.water udes.")+
  theme_classic2()+
  scale_x_discrete(labels= treat.labels)+
  geom_text(data = pval.ph.water_emmeans, aes(x= treatment, y= emmean, label= sign), nudge_x= 0, nudge_y= 1.25)+
  geom_errorbar(data=soil_t0t4_mean, aes(ymin=ph.water_mean-ph.water_sd, 
                                            ymax=ph.water_mean+ph.water_sd, group= time), position=position_dodge(0.9),linewidth =0.2, width=0.2)+
  labs(title = "", subtitle = "", caption = "Different (*) indicates differences between the levels of the treatment factor at each time (T0-T4).\n caculated by Estimated Marginal Means post hoc -Tukey's adjustment method", size = 10)+
  ggtitle("ph.water udes. in T0 and T4\nMean and SD", subtitle= paste("LMEs-Anova III-Time:Treatment(Tukey) p-value: ", format(anova_modelph.watert0t4$`Pr(>F)`[[3]], scientific= TRUE, digits=2 ), sep= ""))+
  guides(fill=guide_legend(title="Treatment"))+
  scale_fill_manual(values = c("#458B74", "#66CDAA"))+ # Add your desired colors
  guides(fill=guide_legend(title="Time"))+
  theme(
    plot.title = element_text(size = 12),
    plot.subtitle = element_text(size = 11),
    plot.caption = element_text(size = 9))
ph.watert0t4_time

ggsave(ph.watert0t4_time, file="soil_parameters_result/ph.watert0t4_time.png", width= 1900,height= 1200, units= "px")


#para hacer el delta, es decir cuanto ha variado la materia organica.. Hay que tener los archivos x separado  
ph.water.t0 <- subset(soilt0t4, soilt0t4$time == "t0")
ph.water.t0 <- data.frame( treatment=ph.water.t0$treatment, ph.water.t0= ph.water.t0$ph.water)
ph.water.t4 <- subset(soilt0t4, soilt0t4$time == "t4")
ph.water.t4 <- data.frame( treatment=ph.water.t4$treatment, ph.water.t4= ph.water.t4$ph.water)

delta.ph.water <- data.frame(treatment= ph.water.t0$treatment,t4= ph.water.t4$ph.water.t4 ,t0= ph.water.t0$ph.water.t0)
delta.ph.water$delta <- delta.ph.water$t4-delta.ph.water$t0
#delta.mat.org$ratio <- delta.mat.org$t4/delta.mat.org$t0
delta.ph.water

delta.ph.water.lm <- lm(delta ~ treatment, data=delta.ph.water) #modelo normal 
delta.ph.water.lm 
anova_deltaph.watert0t4 <-anova(delta.ph.water.lm)#p value 0.005198
anova_deltaph.watert0t4
emm_delta_ph.water_lm <- emmeans(delta.ph.water.lm, pairwise ~  treatment)
emm_delta_ph.water_lm
emm_delta_ph.water_lm$contrasts %>% rbind(adjust= "fdr") %>% summary(infer = TRUE)
emm_delta_ph.water_lm <- cld(emmeans(delta.ph.water.lm, specs = pairwise~treatment), Letters= letters, reversed= TRUE)
emm_delta_ph.water_lm


plotdeltaph.water <- delta.ph.water %>% ggplot(aes(x=factor(treatment, level= treat.order), y= delta, fill= treatment))+
  geom_point(pch= 23, size= 7)+
  xlab("")+
  ylab("ph.waterrus Δ variation between t4-t0")+
  geom_hline(yintercept= 0, linetype = "dashed", color = "red")+
  scale_fill_manual(values= treat.colors)+
  geom_text(data= emm_delta_ph.water_lm, aes(x= treatment, y= emmean, label= `.group`), nudge_x = 0.2, nudge_y = 0.2)+
  guides(fill=guide_legend(title="Treatment"))+
  scale_x_discrete(labels= treat.labels)+
  theme_classic2()+
  labs(title = "", subtitle = "", caption = "Different letters indicates differences between the levels of the treatment factor in delta variation (T4-T0).\n caculated by Estimated Marginal Means post hoc -Tukey's adjustment method.", size = 10)+
  ggtitle("ph.waterrus mg/kg Δ variation T0 between T4", subtitle= paste("LinealModel-Anova Treatment(Tukey) p-value: ", format(anova_deltaph.watert0t4$`Pr(>F)`[[1]], scientific= TRUE, digits=2 ), sep= ""))+
  theme(
    plot.title = element_text(size = 11),
    plot.subtitle = element_text(size = 10),
    plot.caption = element_text(size = 8))

plotdeltaph.water
#Positive values in the delta column indicate an increase in org.matter from t0 to t4.
#Negative values in the delta column indicate a decrease in org.matter from t0 to t4.
ggsave(plotdeltaph.water, file="soil_parameters_result/plotdeltaph_water.png", width= 1900,height= 1200, units= "px")

#ver cuanto de diferente ha sido la variacion delta con respecto a 0

#unir los dos graficos
ph.watert0t4 <- ggarrange(ph.watert0t4_time, plotdeltaph.water)
ph.watert0t4
ggsave(ph.watert0t4, file="soil_parameters_result/ph_watert0t4.png", width= 3800,height= 2200, units= "px")
```

```{r stats conductivity t0t4, echo=FALSE}
shapiro.test(soilt0t4$conductivity) #no normal data
soilt0t4 %>% group_by(treatment) %>% shapiro_test(conductivity) # each treatment are normal.
leveneTest(conductivity~ time * treatment, data=soilt0t4) #equal variances 
model_conduct0t4 <- lmer(conductivity~ time*treatment + (1|treat.pot), data=soilt0t4) 
summary(model_conduct0t4)

anova_modelconduct0t4 <- anova(model_conduct0t4)
anova_modelconduct0t4

emm_conduc <- emmeans(model_conduct0t4, pairwise ~ time | treatment)
emm_conduc
emm_conduc$contrasts %>% rbind(adjust= "fdr") %>% summary(infer = TRUE)#el adjust es para el 
conduccontras <- data.frame(emm_conduc$contrasts)#data frame para sacar el valor del contraste 
conduccontras
conducemmeans <- data.frame(emm_conduc$emmeans) %>% group_by(treatment) %>% summarise(across(.cols= "emmean",.fns=mean),.groups = "drop")#para sacar el valor solo de emmeans
conducemmeans

emm_conduc <- cld(emmeans(model_conduct0t4, specs = pairwise~treatment), Letters= letters, reversed= TRUE)#dif sig y las letras se lo indicas 
emm_conduc #tabla con los resultados. Se hacen dataframe para sacar las columnas que queremos y poder unirlas en los graficos 

pval.conduc_emmeans <- data.frame(treatment= conduccontras$treatment, pval= conduccontras$p.value, emmean= conducemmeans$emmean)
pval.conduc_emmeans
pval.conduc_emmeans$sign <- ifelse(pval.conduc_emmeans$pval>0.05, paste("ns"),
                                 ifelse(pval.conduc_emmeans$pval>0.01, paste("*"),
                                        ifelse(pval.conduc_emmeans$pval> 0.001,
                                               paste("**"), paste("***"))))#para add la significancia con el condicional ifelse


conduct0t4_time <- soil_t0t4_mean %>% ggplot(aes(x=factor(treatment, level= treat.order), y= conductivity_mean), col=time)+
  geom_col(aes(fill= time), col= "black", position= "dodge")+
  xlab("")+
  ylab("conductivity mS/cm.")+
  theme_classic2()+
  scale_x_discrete(labels= treat.labels)+
  geom_text(data = pval.conduc_emmeans, aes(x= treatment, y= emmean, label= sign), nudge_x= 0, nudge_y= 0.2)+
  geom_errorbar(data=soil_t0t4_mean, aes(ymin=conductivity_mean-conductivity_sd, 
                                            ymax=conductivity_mean+conductivity_sd, group= time), position=position_dodge(0.9),linewidth =0.2, width=0.2)+
  labs(title = "", subtitle = "", caption = "Different (*) indicates differences between the levels of the treatment factor at each time (T0-T4).\n caculated by Estimated Marginal Means post hoc -Tukey's adjustment method", size = 10)+
  ggtitle("Conductivity in T0 and T4\nMean and SD", subtitle= paste("LMEs-Anova III-Time:Treatment(Tukey) p-value: ", format(anova_modelconduct0t4$`Pr(>F)`[[3]], scientific= TRUE, digits=2 ), sep= ""))+
  guides(fill=guide_legend(title="Treatment"))+
  scale_fill_manual(values = c("#458B74", "#66CDAA"))+ # Add your desired colors
  guides(fill=guide_legend(title="Time"))+
  theme(
    plot.title = element_text(size = 12),
    plot.subtitle = element_text(size = 11),
    plot.caption = element_text(size = 9))
conduct0t4_time

ggsave(conduct0t4_time, file="soil_parameters_result/conduct0t4_time.png", width= 1900,height= 1200, units= "px")


#para hacer el delta, es decir cuanto ha variado la materia organica.. Hay que tener los archivos x separado  
conduc.t0 <- subset(soilt0t4, soilt0t4$time == "t0")
conduc.t0 <- data.frame( treatment=conduc.t0$treatment, conduc.t0= conduc.t0$conductivity)
conduc.t4 <- subset(soilt0t4, soilt0t4$time == "t4")
conduc.t4 <- data.frame( treatment=conduc.t4$treatment, conduc.t4= conduc.t4$conductivity)

delta.ph.water <- data.frame(treatment= ph.water.t0$treatment,t4= ph.water.t4$ph.water.t4 ,t0= ph.water.t0$ph.water.t0)


delta.conduc <- data.frame(treatment= conduc.t0$treatment, t4=conduc.t4$conduc.t4, t0=conduc.t0$conduc.t0)

delta.conduc$delta <- delta.conduc$t4-delta.conduc$t0
#delta.mat.org$ratio <- delta.mat.org$t4/delta.mat.org$t0
delta.conduc

delta.conduc.lm <- lm(delta ~ treatment, data=delta.conduc) #modelo normal 
delta.conduc.lm 
anova_deltaconduct0t4 <-anova(delta.conduc.lm)#p value 0.0004265
anova_deltaconduct0t4
emm_delta_conduc_lm <- emmeans(delta.conduc.lm, pairwise ~  treatment)
emm_delta_conduc_lm
emm_delta_conduc_lm$contrasts %>% rbind(adjust= "fdr") %>% summary(infer = TRUE)
emm_delta_conduc_lm <- cld(emmeans(delta.conduc.lm, specs = pairwise~treatment), Letters= letters, reversed= TRUE)
emm_delta_conduc_lm


plotdeltaconduc <- delta.conduc %>% ggplot(aes(x=factor(treatment, level= treat.order), y= delta, fill= treatment))+
  geom_point(pch= 23, size= 7)+
  xlab("")+
  ylab(" Δ conductivity variation between t4-t0")+
  geom_hline(yintercept= 0, linetype = "dashed", color = "red")+
  scale_fill_manual(values= treat.colors)+
  geom_text(data= emm_delta_conduc_lm, aes(x= treatment, y= emmean, label= `.group`), nudge_x = 0.2, nudge_y = 0.2)+
  guides(fill=guide_legend(title="Treatment"))+
  scale_x_discrete(labels= treat.labels)+
  theme_classic2()+
  labs(title = "", subtitle = "", caption = "Different letters indicates differences between the levels of the treatment factor in delta variation (T4-T0).\n caculated by Estimated Marginal Means post hoc -Tukey's adjustment method.", size = 10)+
  ggtitle("Conductivity Δ variation T0 between T4", subtitle= paste("LinealModel-Anova Treatment(Tukey) p-value: ", format(anova_deltaconduct0t4$`Pr(>F)`[[1]], scientific= TRUE, digits=2 ), sep= ""))+
  theme(
    plot.title = element_text(size = 11),
    plot.subtitle = element_text(size = 10),
    plot.caption = element_text(size = 8))

plotdeltaconduc
#Positive values in the delta column indicate an increase in org.matter from t0 to t4.
#Negative values in the delta column indicate a decrease in org.matter from t0 to t4.
ggsave(plotdeltaconduc, file="soil_parameters_result/plotdeltaconduc.png", width= 1900,height= 1200, units= "px")

#ver cuanto de diferente ha sido la variacion delta con respecto a 0

#unir los dos graficos
conduct0t4 <- ggarrange(conduct0t4_time, plotdeltaconduc)
conduct0t4
ggsave(conduct0t4, file="soil_parameters_result/conduct0t4.png", width= 3800,height= 2200, units= "px")

```


```{r stas calcium t0t4, echo=FALSE}
shapiro.test(soilt0t4$calcium) # normal data
leveneTest(calcium ~ time * treatment, data=soilt0t4) #equal variances
model_calciumt0t4 <- lmer(calcium~ time*treatment + (1|treat.pot), data=soilt0t4) 
summary(model_calciumt0t4)

anova_modelcalciumt0t4 <- anova(model_calciumt0t4)
anova_modelcalciumt0t4

emm_calcium <- emmeans(model_calciumt0t4, pairwise ~ time | treatment)
emm_calcium
emm_calcium$contrasts %>% rbind(adjust= "fdr") %>% summary(infer = TRUE)#el adjust es para el 
calciumcontras <- data.frame(emm_calcium$contrasts)#data frame para sacar el valor del contraste 
calciumcontras
calciumemmeans <- data.frame(emm_calcium$emmeans) %>% group_by(treatment) %>% summarise(across(.cols= "emmean",.fns=mean),.groups = "drop")#para sacar el valor solo de emmeans
calciumemmeans

emm_calcium <- cld(emmeans(model_calciumt0t4, specs = pairwise~treatment), Letters= letters, reversed= TRUE)#dif sig y las letras se lo indicas 
emm_calcium #tabla con los resultados. Se hacen dataframe para sacar las columnas que queremos y poder unirlas en los graficos 

pval.calcium_emmeans <- data.frame(treatment= calciumcontras$treatment, pval= calciumcontras$p.value, emmean= calciumemmeans$emmean)
pval.calcium_emmeans
pval.calcium_emmeans$sign <- ifelse(pval.calcium_emmeans$pval>0.05, paste("ns"),
                                 ifelse(pval.calcium_emmeans$pval>0.01, paste("*"),
                                        ifelse(pval.calcium_emmeans$pval> 0.001,
                                               paste("**"), paste("***"))))#para add la significancia con el condicional ifelse


calciumt0t4_time <- soil_t0t4_mean %>% ggplot(aes(x=factor(treatment, level= treat.order), y= calcium_mean), col=time)+
  geom_col(aes(fill= time), col= "black", position= "dodge")+
  xlab("")+
  ylab("calcium mEq/kg.")+
  theme_classic2()+
  scale_x_discrete(labels= treat.labels)+
  geom_text(data = pval.calcium_emmeans, aes(x= treatment, y= emmean, label= sign), nudge_x= 0, nudge_y= 15)+
  geom_errorbar(data=soil_t0t4_mean, aes(ymin=calcium_mean-calcium_sd, 
                                            ymax=calcium_mean+calcium_sd, group= time), position=position_dodge(0.9),linewidth =0.2, width=0.2)+
  labs(title = "", subtitle = "", caption = "Different (*) indicates differences between the levels of the treatment factor at each time (T0-T4).\n caculated by Estimated Marginal Means post hoc -Tukey's adjustment method", size = 10)+
  ggtitle("Calcium in T0 and T4\nMean and SD", subtitle= paste("LMEs-Anova III-Time:Treatment(Tukey) p-value: ", format(anova_modelcalciumt0t4$`Pr(>F)`[[3]], scientific= TRUE, digits=2 ), sep= ""))+
  guides(fill=guide_legend(title="Treatment"))+
  scale_fill_manual(values = c("#458B74", "#66CDAA"))+ # Add your desired colors
  guides(fill=guide_legend(title="Time"))+
  theme(
    plot.title = element_text(size = 12),
    plot.subtitle = element_text(size = 11),
    plot.caption = element_text(size = 9))
calciumt0t4_time
ggsave(calciumt0t4_time, file="soil_parameters_result/calciumt0t4_time.png", width= 1900,height= 1200, units= "px")


#para hacer el delta, es decir cuanto ha variado la materia organica.. Hay que tener los archivos x separado  
calcium.t0 <- subset(soilt0t4, soilt0t4$time == "t0")
calcium.t0 <- data.frame( treatment=calcium.t0$treatment, calcium.t0= calcium.t0$calcium)
calcium.t4 <- subset(soilt0t4, soilt0t4$time == "t4")
calcium.t4 <- data.frame( treatment=calcium.t4$treatment, calcium.t4= calcium.t4$calcium)

delta.calcium <- data.frame(treatment= calcium.t0$treatment, t4=calcium.t4$calcium.t4, t0=calcium.t0$calcium.t0)

delta.calcium$delta <- delta.calcium$t4-delta.calcium$t0
#delta.mat.org$ratio <- delta.mat.org$t4/delta.mat.org$t0
delta.calcium

delta.calcium.lm <- lm(delta ~ treatment, data=delta.calcium) #modelo normal 
#delta.calcium.lm0 <- lm(delta ~ 0 + treatment, data=delta.calcium) #modelo normal 
summary(delta.calcium.lm0)

anova.calciumlmo0<-anova(delta.calcium.lm0)
summary(anova.calciumlmo0)

delta.calcium.lm 
anova_deltacalciumt0t4 <-anova(delta.calcium.lm)#p value 0.0004265
anova_deltacalciumt0t4
emm_delta_calcium_lm <- emmeans(delta.calcium.lm, pairwise ~  treatment)
emm_delta_calcium_lm
emm_delta_calcium_lm$contrasts %>% rbind(adjust= "fdr") %>% summary(infer = TRUE)
emm_delta_calcium_lm <- cld(emmeans(delta.calcium.lm, specs = pairwise~treatment), Letters= letters, reversed= TRUE)
emm_delta_calcium_lm


plotdeltacalcium <- delta.calcium %>% ggplot(aes(x=factor(treatment, level= treat.order), y= delta, fill= treatment))+
  geom_point(pch= 23, size= 7)+
  xlab("")+
  ylab(" Δ calciumtivity variation between t4-t0")+
  geom_hline(yintercept= 0, linetype = "dashed", color = "red")+
  scale_fill_manual(values= treat.colors)+
  geom_text(data= emm_delta_calcium_lm, aes(x= treatment, y= emmean, label= `.group`), nudge_x = 0.2, nudge_y = 0.2)+
  guides(fill=guide_legend(title="Treatment"))+
  scale_x_discrete(labels= treat.labels)+
  theme_classic2()+
  labs(title = "", subtitle = "", caption = "Different letters indicates differences between the levels of the treatment factor in delta variation (T4-T0).\n caculated by Estimated Marginal Means post hoc -Tukey's adjustment method.", size = 10)+
  ggtitle("Calcium Δ variation T0 between T4", subtitle= paste("LinealModel-Anova Treatment(Tukey) p-value: ", format(anova_deltacalciumt0t4$`Pr(>F)`[[1]], scientific= TRUE, digits=2 ), sep= ""))+
  theme(
    plot.title = element_text(size = 11),
    plot.subtitle = element_text(size = 10),
    plot.caption = element_text(size = 8))

plotdeltacalcium
ggsave(plotdeltacalcium, file="soil_parameters_result/plotdeltacalcium.png", width= 1900,height= 1200, units= "px")
calciumt0t4 <- ggarrange(calciumt0t4_time, plotdeltacalcium)
calciumt0t4
ggsave(calciumt0t4, file="soil_parameters_result/calciumt0t4.png", width= 3800,height= 2200, units= "px")
```

```{r stats sodium t0t4, echo=FALSE}
shapiro.test(soilt0t4$sodium) # no normal data
soilt0t4 %>% group_by(treatment) %>% shapiro_test(sodium) # each treatment are normal in the different times. 
leveneTest(sodium ~ time * treatment, data=soilt0t4) #equal variances 
model_sodiumt0t4 <- lmer(sodium~ time*treatment + (1|treat.pot), data=soilt0t4) 
summary(model_sodiumt0t4)

anova_modelsodiumt0t4 <- anova(model_sodiumt0t4)
anova_modelsodiumt0t4

emm_sodium <- emmeans(model_sodiumt0t4, pairwise ~ time | treatment)
emm_sodium
emm_sodium$contrasts %>% rbind(adjust= "fdr") %>% summary(infer = TRUE)#el adjust es para el 
sodiumcontras <- data.frame(emm_sodium$contrasts)#data frame para sacar el valor del contraste 
sodiumcontras
sodiumemmeans <- data.frame(emm_sodium$emmeans) %>% group_by(treatment) %>% summarise(across(.cols= "emmean",.fns=mean),.groups = "drop")#para sacar el valor solo de emmeans
sodiumemmeans

emm_sodium <- cld(emmeans(model_sodiumt0t4, specs = pairwise~treatment), Letters= letters, reversed= TRUE)#dif sig y las letras se lo indicas 
emm_sodium #tabla con los resultados. Se hacen dataframe para sacar las columnas que queremos y poder unirlas en los graficos 

pval.sodium_emmeans <- data.frame(treatment= sodiumcontras$treatment, pval= sodiumcontras$p.value, emmean= sodiumemmeans$emmean)
pval.sodium_emmeans
pval.sodium_emmeans$sign <- ifelse(pval.sodium_emmeans$pval>0.05, paste("ns"),
                                 ifelse(pval.sodium_emmeans$pval>0.01, paste("*"),
                                        ifelse(pval.sodium_emmeans$pval> 0.001,
                                               paste("**"), paste("***"))))#para add la significancia con el condicional ifelse


sodiumt0t4_time <- soil_t0t4_mean %>% ggplot(aes(x=factor(treatment, level= treat.order), y= sodium_mean), col=time)+
  geom_col(aes(fill= time), col= "black", position= "dodge")+
  xlab("")+
  ylab("sodium mEq/kg.")+
  theme_classic2()+
  scale_x_discrete(labels= treat.labels)+
  geom_text(data = pval.sodium_emmeans, aes(x= treatment, y= emmean, label= sign), nudge_x= 0, nudge_y= 15)+
  geom_errorbar(data=soil_t0t4_mean, aes(ymin=sodium_mean-sodium_sd, 
                                            ymax=sodium_mean+sodium_sd, group= time), position=position_dodge(0.9),linewidth =0.2, width=0.2)+
  labs(title = "", subtitle = "", caption = "Different (*) indicates differences between the levels of the treatment factor at each time (T0-T4).\n caculated by Estimated Marginal Means post hoc -Tukey's adjustment method", size = 10)+
  ggtitle("sodium in T0 and T4\nMean and SD", subtitle= paste("LMEs-Anova III-Time:Treatment(Tukey) p-value: ", format(anova_modelsodiumt0t4$`Pr(>F)`[[3]], scientific= TRUE, digits=2 ), sep= ""))+
  guides(fill=guide_legend(title="Treatment"))+
  scale_fill_manual(values = c("#458B74", "#66CDAA"))+ # Add your desired colors
  guides(fill=guide_legend(title="Time"))+
  theme(
    plot.title = element_text(size = 12),
    plot.subtitle = element_text(size = 11),
    plot.caption = element_text(size = 9))
sodiumt0t4_time
ggsave(sodiumt0t4_time, file="soil_parameters_result/sodiumt0t4_time.png", width= 1900,height= 1200, units= "px")


#para hacer el delta, es decir cuanto ha variado la materia organica.. Hay que tener los archivos x separado  
sodium.t0 <- subset(soilt0t4, soilt0t4$time == "t0")
sodium.t0 <- data.frame( treatment=sodium.t0$treatment, sodium.t0= sodium.t0$sodium)
sodium.t4 <- subset(soilt0t4, soilt0t4$time == "t4")
sodium.t4 <- data.frame( treatment=sodium.t4$treatment, sodium.t4= sodium.t4$sodium)

delta.sodium <- data.frame(treatment= sodium.t0$treatment, t4=sodium.t4$sodium.t4, t0=sodium.t0$sodium.t0)

delta.sodium$delta <- delta.sodium$t4-delta.sodium$t0
#delta.mat.org$ratio <- delta.mat.org$t4/delta.mat.org$t0
delta.sodium

delta.sodium.lm <- lm(delta ~ treatment, data=delta.sodium) #modelo normal 
delta.sodium.lm 
anova_deltasodiumt0t4 <-anova(delta.sodium.lm)#p value 0.0004265
anova_deltasodiumt0t4
emm_delta_sodium_lm <- emmeans(delta.sodium.lm, pairwise ~  treatment)
emm_delta_sodium_lm
emm_delta_sodium_lm$contrasts %>% rbind(adjust= "fdr") %>% summary(infer = TRUE)
emm_delta_sodium_lm <- cld(emmeans(delta.sodium.lm, specs = pairwise~treatment), Letters= letters, reversed= TRUE)
emm_delta_sodium_lm


plotdeltasodium <- delta.sodium %>% ggplot(aes(x=factor(treatment, level= treat.order), y= delta, fill= treatment))+
  geom_point(pch= 23, size= 7)+
  xlab("")+
  ylab(" Δ sodiumtivity variation between t4-t0")+
  geom_hline(yintercept= 0, linetype = "dashed", color = "red")+
  scale_fill_manual(values= treat.colors)+
  geom_text(data= emm_delta_sodium_lm, aes(x= treatment, y= emmean, label= `.group`), nudge_x = 0.2, nudge_y = 0.2)+
  guides(fill=guide_legend(title="Treatment"))+
  scale_x_discrete(labels= treat.labels)+
  theme_classic2()+
  labs(title = "", subtitle = "", caption = "Different letters indicates differences between the levels of the treatment factor in delta variation (T4-T0).\n caculated by Estimated Marginal Means post hoc -Tukey's adjustment method.", size = 10)+
  ggtitle("sodium Δ variation T0 between T4", subtitle= paste("LinealModel-Anova Treatment(Tukey) p-value: ", format(anova_deltasodiumt0t4$`Pr(>F)`[[1]], scientific= TRUE, digits=2 ), sep= ""))+
  theme(
    plot.title = element_text(size = 11),
    plot.subtitle = element_text(size = 10),
    plot.caption = element_text(size = 8))

plotdeltasodium
ggsave(plotdeltasodium, file="soil_parameters_result/plotdeltasodium.png", width= 1900,height= 1200, units= "px")
sodiumt0t4 <- ggarrange(sodiumt0t4_time, plotdeltasodium)
sodiumt0t4
ggsave(sodiumt0t4, file="soil_parameters_result/sodiumt0t4.png", width= 3800,height= 2200, units= "px")

```

```{r stats potassium t0t4, echo=FALSE}
shapiro.test(soilt0t4$potassium) #normal data
leveneTest(potassium ~ time * treatment, data=soilt0t4) #equal variances
model_potassiumt0t4 <- lmer(potassium~ time*treatment + (1|treat.pot), data=soilt0t4) 
summary(model_potassiumt0t4)

anova_modelpotassiumt0t4 <- anova(model_potassiumt0t4)
anova_modelpotassiumt0t4

emm_potassium <- emmeans(model_potassiumt0t4, pairwise ~ time | treatment)
emm_potassium
emm_potassium$contrasts %>% rbind(adjust= "fdr") %>% summary(infer = TRUE)#el adjust es para el 
potassiumcontras <- data.frame(emm_potassium$contrasts)#data frame para sacar el valor del contraste 
potassiumcontras
potassiumemmeans <- data.frame(emm_potassium$emmeans) %>% group_by(treatment) %>% summarise(across(.cols= "emmean",.fns=mean),.groups = "drop")#para sacar el valor solo de emmeans
potassiumemmeans

emm_potassium <- cld(emmeans(model_potassiumt0t4, specs = pairwise~treatment), Letters= letters, reversed= TRUE)#dif sig y las letras se lo indicas 
emm_potassium #tabla con los resultados. Se hacen dataframe para sacar las columnas que queremos y poder unirlas en los graficos 

pval.potassium_emmeans <- data.frame(treatment= potassiumcontras$treatment, pval= potassiumcontras$p.value, emmean= potassiumemmeans$emmean)
pval.potassium_emmeans
pval.potassium_emmeans$sign <- ifelse(pval.potassium_emmeans$pval>0.05, paste("ns"),
                                 ifelse(pval.potassium_emmeans$pval>0.01, paste("*"),
                                        ifelse(pval.potassium_emmeans$pval> 0.001,
                                               paste("**"), paste("***"))))#para add la significancia con el condicional ifelse


potassiumt0t4_time <- soil_t0t4_mean %>% ggplot(aes(x=factor(treatment, level= treat.order), y= potassium_mean), col=time)+
  geom_col(aes(fill= time), col= "black", position= "dodge")+
  xlab("")+
  ylab("potassium mEq/kg.")+
  theme_classic2()+
  scale_x_discrete(labels= treat.labels)+
  geom_text(data = pval.potassium_emmeans, aes(x= treatment, y= emmean, label= sign), nudge_x= 0, nudge_y= 5)+
  geom_errorbar(data=soil_t0t4_mean, aes(ymin=potassium_mean-potassium_sd, 
                                            ymax=potassium_mean+potassium_sd, group= time), position=position_dodge(0.9),linewidth =0.2, width=0.2)+
  labs(title = "", subtitle = "", caption = "Different (*) indicates differences between the levels of the treatment factor at each time (T0-T4).\n caculated by Estimated Marginal Means post hoc -Tukey's adjustment method", size = 10)+
  ggtitle("potassium in T0 and T4\nMean and SD", subtitle= paste("LMEs-Anova III-Time:Treatment(Tukey) p-value: ", format(anova_modelpotassiumt0t4$`Pr(>F)`[[3]], scientific= TRUE, digits=2 ), sep= ""))+
  guides(fill=guide_legend(title="Treatment"))+
  scale_fill_manual(values = c("#458B74", "#66CDAA"))+ # Add your desired colors
  guides(fill=guide_legend(title="Time"))+
  theme(
    plot.title = element_text(size = 12),
    plot.subtitle = element_text(size = 11),
    plot.caption = element_text(size = 9))
potassiumt0t4_time
ggsave(potassiumt0t4_time, file="soil_parameters_result/potassiumt0t4_time.png", width= 1900,height= 1200, units= "px")


#para hacer el delta, es decir cuanto ha variado la materia organica.. Hay que tener los archivos x separado  
potassium.t0 <- subset(soilt0t4, soilt0t4$time == "t0")
potassium.t0 <- data.frame( treatment=potassium.t0$treatment, potassium.t0= potassium.t0$potassium)
potassium.t4 <- subset(soilt0t4, soilt0t4$time == "t4")
potassium.t4 <- data.frame( treatment=potassium.t4$treatment, potassium.t4= potassium.t4$potassium)

delta.potassium <- data.frame(treatment= potassium.t0$treatment, t4=potassium.t4$potassium.t4, t0=potassium.t0$potassium.t0)

delta.potassium$delta <- delta.potassium$t4-delta.potassium$t0
#delta.mat.org$ratio <- delta.mat.org$t4/delta.mat.org$t0
delta.potassium

delta.potassium.lm <- lm(delta ~ treatment, data=delta.potassium) #modelo normal 
delta.potassium.lm 
anova_deltapotassiumt0t4 <-anova(delta.potassium.lm)#p value 0.0004265
anova_deltapotassiumt0t4
emm_delta_potassium_lm <- emmeans(delta.potassium.lm, pairwise ~  treatment)
emm_delta_potassium_lm
emm_delta_potassium_lm$contrasts %>% rbind(adjust= "fdr") %>% summary(infer = TRUE)
emm_delta_potassium_lm <- cld(emmeans(delta.potassium.lm, specs = pairwise~treatment), Letters= letters, reversed= TRUE)
emm_delta_potassium_lm


plotdeltapotassium <- delta.potassium %>% ggplot(aes(x=factor(treatment, level= treat.order), y= delta, fill= treatment))+
  geom_point(pch= 23, size= 7)+
  xlab("")+
  ylab(" Δ potassiumtivity variation between t4-t0")+
  geom_hline(yintercept= 0, linetype = "dashed", color = "red")+
  scale_fill_manual(values= treat.colors)+
  geom_text(data= emm_delta_potassium_lm, aes(x= treatment, y= emmean, label= `.group`), nudge_x = 0.2, nudge_y = 0.2)+
  guides(fill=guide_legend(title="Treatment"))+
  scale_x_discrete(labels= treat.labels)+
  theme_classic2()+
  labs(title = "", subtitle = "", caption = "Different letters indicates differences between the levels of the treatment factor in delta variation (T4-T0).\n caculated by Estimated Marginal Means post hoc -Tukey's adjustment method.", size = 10)+
  ggtitle("potassium Δ variation T0 between T4", subtitle= paste("LinealModel-Anova Treatment(Tukey) p-value: ", format(anova_deltapotassiumt0t4$`Pr(>F)`[[1]], scientific= TRUE, digits=2 ), sep= ""))+
  theme(
    plot.title = element_text(size = 11),
    plot.subtitle = element_text(size = 10),
    plot.caption = element_text(size = 8))

plotdeltapotassium
ggsave(plotdeltapotassium, file="soil_parameters_result/plotdeltapotassium.png", width= 1900,height= 1200, units= "px")

potassiumt0t4 <- ggarrange(potassiumt0t4_time, plotdeltapotassium)
potassiumt0t4
ggsave(potassiumt0t4, file="soil_parameters_result/potassiumt0t4.png", width= 3800,height= 2200, units= "px")


```


```{r stats nitrogen t0t4, echo=FALSE}
shapiro.test(soilt0t4$nitrogen) #normal data
leveneTest(nitrogen ~ time * treatment, data=soilt0t4) #equal variances
model_nitrogent0t4 <- lmer(nitrogen~ time*treatment + (1|treat.pot), data=soilt0t4) 
summary(model_nitrogent0t4)

anova_modelnitrogent0t4 <- anova(model_nitrogent0t4)
anova_modelnitrogent0t4

emm_nitrogen <- emmeans(model_nitrogent0t4, pairwise ~ time | treatment)
emm_nitrogen
emm_nitrogen$contrasts %>% rbind(adjust= "fdr") %>% summary(infer = TRUE)#el adjust es para el 
nitrogencontras <- data.frame(emm_nitrogen$contrasts)#data frame para sacar el valor del contraste 
nitrogencontras
nitrogenemmeans <- data.frame(emm_nitrogen$emmeans) %>% group_by(treatment) %>% summarise(across(.cols= "emmean",.fns=mean),.groups = "drop")#para sacar el valor solo de emmeans
nitrogenemmeans

emm_nitrogen <- cld(emmeans(model_nitrogent0t4, specs = pairwise~treatment), Letters= letters, reversed= TRUE)#dif sig y las letras se lo indicas 
emm_nitrogen #tabla con los resultados. Se hacen dataframe para sacar las columnas que queremos y poder unirlas en los graficos 

pval.nitrogen_emmeans <- data.frame(treatment= nitrogencontras$treatment, pval= nitrogencontras$p.value, emmean= nitrogenemmeans$emmean)
pval.nitrogen_emmeans
pval.nitrogen_emmeans$sign <- ifelse(pval.nitrogen_emmeans$pval>0.05, paste("ns"),
                                 ifelse(pval.nitrogen_emmeans$pval>0.01, paste("*"),
                                        ifelse(pval.nitrogen_emmeans$pval> 0.001,
                                               paste("**"), paste("***"))))#para add la significancia con el condicional ifelse


nitrogent0t4_time <- soil_t0t4_mean %>% ggplot(aes(x=factor(treatment, level= treat.order), y= nitrogen_mean), col=time)+
  geom_col(aes(fill= time), col= "black", position= "dodge")+
  xlab("")+
  ylab("nitrogen mEq/kg.")+
  theme_classic2()+
  scale_x_discrete(labels= treat.labels)+
  geom_text(data = pval.nitrogen_emmeans, aes(x= treatment, y= emmean, label= sign), nudge_x= 0, nudge_y= 0.05)+
  geom_errorbar(data=soil_t0t4_mean, aes(ymin=nitrogen_mean-nitrogen_sd, 
                                            ymax=nitrogen_mean+nitrogen_sd, group= time), position=position_dodge(0.9),linewidth =0.2, width=0.2)+
  labs(title = "", subtitle = "", caption = "Different (*) indicates differences between the levels of the treatment factor at each time (T0-T4).\n caculated by Estimated Marginal Means post hoc -Tukey's adjustment method", size = 10)+
  ggtitle("Nitrogen in T0 and T4\nMean and SD", subtitle= paste("LMEs-Anova III-Time:Treatment(Tukey) p-value: ", format(anova_modelnitrogent0t4$`Pr(>F)`[[3]], scientific= TRUE, digits=2 ), sep= ""))+
  guides(fill=guide_legend(title="Treatment"))+
  scale_fill_manual(values = c("#458B74", "#66CDAA"))+ # Add your desired colors
  guides(fill=guide_legend(title="Time"))+
  theme(
    plot.title = element_text(size = 12),
    plot.subtitle = element_text(size = 11),
    plot.caption = element_text(size = 9))
nitrogent0t4_time
ggsave(nitrogent0t4_time, file="soil_parameters_result/nitrogent0t4_time.png", width= 1900,height= 1200, units= "px")


#para hacer el delta, es decir cuanto ha variado la materia organica.. Hay que tener los archivos x separado  
nitrogen.t0 <- subset(soilt0t4, soilt0t4$time == "t0")
nitrogen.t0 <- data.frame( treatment=nitrogen.t0$treatment, nitrogen.t0= nitrogen.t0$nitrogen)
nitrogen.t4 <- subset(soilt0t4, soilt0t4$time == "t4")
nitrogen.t4 <- data.frame( treatment=nitrogen.t4$treatment, nitrogen.t4= nitrogen.t4$nitrogen)

delta.nitrogen <- data.frame(treatment= nitrogen.t0$treatment, t4=nitrogen.t4$nitrogen.t4, t0=nitrogen.t0$nitrogen.t0)

delta.nitrogen$delta <- delta.nitrogen$t4-delta.nitrogen$t0
#delta.mat.org$ratio <- delta.mat.org$t4/delta.mat.org$t0
delta.nitrogen

delta.nitrogen.lm <- lm(delta ~ treatment, data=delta.nitrogen) #modelo normal 
delta.nitrogen.lm 
anova_deltanitrogent0t4 <-anova(delta.nitrogen.lm)#p value 0.0004265
anova_deltanitrogent0t4
emm_delta_nitrogen_lm <- emmeans(delta.nitrogen.lm, pairwise ~  treatment)
emm_delta_nitrogen_lm
emm_delta_nitrogen_lm$contrasts %>% rbind(adjust= "fdr") %>% summary(infer = TRUE)
emm_delta_nitrogen_lm <- cld(emmeans(delta.nitrogen.lm, specs = pairwise~treatment), Letters= letters, reversed= TRUE)
emm_delta_nitrogen_lm


plotdeltanitrogen <- delta.nitrogen %>% ggplot(aes(x=factor(treatment, level= treat.order), y= delta, fill= treatment))+
  geom_point(pch= 23, size= 7)+
  xlab("")+
  ylab(" Δ nitrogentivity variation between t4-t0")+
  geom_hline(yintercept= 0, linetype = "dashed", color = "red")+
  scale_fill_manual(values= treat.colors)+
  geom_text(data= emm_delta_nitrogen_lm, aes(x= treatment, y= emmean, label= `.group`), nudge_x = 0.2, nudge_y = 0.02)+
  guides(fill=guide_legend(title="Treatment"))+
  scale_x_discrete(labels= treat.labels)+
  theme_classic2()+
  labs(title = "", subtitle = "", caption = "Different letters indicates differences between the levels of the treatment factor in delta variation (T4-T0).\n caculated by Estimated Marginal Means post hoc -Tukey's adjustment method.", size = 10)+
  ggtitle("nitrogen Δ variation T0 between T4", subtitle= paste("LinealModel-Anova Treatment(Tukey) p-value: ", format(anova_deltanitrogent0t4$`Pr(>F)`[[1]], scientific= TRUE, digits=2 ), sep= ""))+
  theme(
    plot.title = element_text(size = 11),
    plot.subtitle = element_text(size = 10),
    plot.caption = element_text(size = 8))

plotdeltanitrogen
ggsave(plotdeltanitrogen, file="soil_parameters_result/plotdeltanitrogen.png", width= 1900,height= 1200, units= "px")
nitrogent0t4 <- ggarrange(nitrogent0t4_time, plotdeltanitrogen)
nitrogent0t4
ggsave(nitrogent0t4, file="soil_parameters_result/nitrogent0t4.png", width= 3800,height= 2200, units= "px")

```

